<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="FIDEL-PC" failures="2" tests="2" name="Default test(failed)" time="0.336" errors="0" timestamp="2024-10-07T17:50:34 WAT">
  <testcase classname="demo.TestNGRetryFailedDemo" name="test3" time="0.066">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at demo.TestNGRetryFailedDemo.test3(TestNGRetryFailedDemo.java:22)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase classname="demo.TestNGRetryFailedDemo" name="test2" time="0.02">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at demo.TestNGRetryFailedDemo.test2(TestNGRetryFailedDemo.java:16)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="demo.TestNGRetryFailedDemo" name="test1" time="0.0">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Default test(failed) -->
